language: android
jdk: oraclejdk8
cache: false
sudo: true

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default - see #247)

addons:
  apt:
    packages:
      - lynx

android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean build -PdisablePreDex --stacktrace

after_failure:
  - lynx -dump /home/travis/build/protoman92/KotlinRedux/common/core/build/reports/tests/test/index.html
